### ISSUE TITLE
Mujoco XML files for models

### ISSUE THREAD

**Issue by vighv** [MyoHub/myo_sim#11]
Hi,
Will you be releasing the XML files corresponding to the MJB binaries? Would really help if we want to tinker with the models, by adding on an exoskeleton or simulating sarcopenia.

If not, any suggestions on how to do these mods with just the binaries?

**Comment by Vittorio-Caggiano** [comment]
Hi @vighv , have you looked at [MyoSuite](https://github.com/facebookresearch/MyoSuite)? There you can find both how to example how to control [models with an exoskeleton](https://myosuite.readthedocs.io/en/latest/suite.html) e.g. `myoSarcElbowPose1D6MRandom-v0` (just sarcopenia) or `myoSarcElbowPose1D6MRandom-v0` (exo + sarcopenia) 

If you want to add new exoskeletons, you can contribute it along the lines of [this example](https://github.com/MyoHub/myo_sim/blob/main/elbow/myoelbow_1dof6muscles_1dofSoftexo_Ideal.xml)
