### ISSUE TITLE
XML file for arm model

### ISSUE THREAD

**Issue by joaobelo92** [MyoHub/myo_sim#12]
Hi, 

Would it be possible to release the arm model as a xml file?

Thanks in advance!

**Comment by Vittorio-Caggiano** [comment]
Hi @joaobelo92 , we are currently using this model for the [MyoChallenge 2023](https://sites.google.com/view/myosuite/myochallenge/myochallenge-2023) and we might be able to share it only after it is completed. Do you have any specific reason to access the xml file? Can we provide what you need in other ways?

**Comment by joaobelo92** [comment]
We want to use it in a project where it would be relevant to be able to modify it. We can wait for the challenge to be over. Thanks for replying and making this available!

**Comment by hiicaptain** [comment]
Hi there, 

I hope this message finds you well. I've been closely following the progress of the MyoChallenge, and I'm truly impressed with the work that's been done. I noticed that the Myochallenge recently ended, so I would be very grateful if you could update the arm's XML file. I would like to try to customize an arm-based environment, so the xml file would be very helpful!

Thank you in advance.

**Comment by Vittorio-Caggiano** [comment]
Hi @hiicaptain thanks for your nice note! We are planning to release this model soon... hold on a few more weeks

**Comment by Vittorio-Caggiano** [comment]
@joaobelo92 @hiicaptain the XMLs files of the arm model are now available in the `main` branch
