### ISSUE TITLE
The .mjb files cannot be run with Mujoco

### ISSUE THREAD

**Issue by NghiaPhamttk27** [MyoHub/myo_sim#14]
I have tried to run any .mjb file with it, but I keep getting the error 'ValueError: mj_loadModel: failed to load from mjb.' I've tried to investigate, but it seems like this is not a Mujoco-related issue. I am using Mujoco version 2.3.7 on Windows 11.

![myosim](https://github.com/MyoHub/myo_sim/assets/145578401/b753889e-9a0f-4023-873e-cae7f7f22cf7)

**Comment by zebin-huang** [comment]
I also noticed that these model files are in ".mjb" format. Could you provide the model files in XML format? This would greatly facilitate customization. Thank you so much!

**Comment by Vittorio-Caggiano** [comment]
Hi @zebin-huang from the screenshot it seems you were trying to load the version compatible with MuJoCo 2.3.6 (myolegs_chasetag_v0.10(mj236))
can you try to load the updated version which should be compatible with 2.3.7 ? https://github.com/MyoHub/myo_sim/blob/main/leg/myolegs_chasetag_v0.11(mj237).mjb

We will be releasing the xml soon.

**Comment by Vittorio-Caggiano** [comment]
@zebin-huang the xmls files of the models are now released... please refer to the `main` branch

@NghiaPhamttk27 please let us know if you have still issues or if those are fixed with the released xmls
