### ISSUE TITLE
Request: adding the suspended myoleg model from myosuite demo

### ISSUE THREAD

**Issue by Leonardo-Corsi** [MyoHub/myo_sim#17]
In the [myosuite demo](https://myohub.github.io/myosuite_demo/) a variant of the myoleg model, called "myoleg (suspended)" can be selected and interacted with. 
It would be great to have this suspended version as well as the classic myoleg as a mujoco xml file here.
I realize that obtaining it should be possible with few changes to the original xml, though the original suspended myoleg implementation could be safer and would be more guaranteed to function as desired.

**Comment by Leonardo-Corsi** [comment]
Quick puntualization: the mujoco binary model can be found in the [myosuite_demo repo](https://github.com/MyoHub/myosuite_demo/tree/main/examples/scenes/myo_sim/myolegs) but since this repo contains all the xml models I supposed that the "issue" fits better here
Thanks!

**Comment by Vittorio-Caggiano** [comment]
Hi Leonardo, we will be releasing soon the xml file of the myoleg. We could add a 'suspended' version of the task as well

cc: @vikashplus @P-Schumacher

**Comment by P-Schumacher** [comment]
I've added the suspended model as PR #19 here [here](https://github.com/MyoHub/myo_sim/pull/19).
@Leonardo-Corsi give it a try and while we merge it into the main branch.

**Comment by Leonardo-Corsi** [comment]
Thanks a lot for the quick reply and the xml model.
It is consistent with my attempt to create it and seems to work smoothly.

For anyone who might need it, I'm also reporting a qpos vector (a possible key_qpos of interest) below, representing the equilibrium condition with no actuation:

0.078594 -0.033019 -0.578070 0.001713 0.000952 0.278114 0.018932 0.090195 -0.280089 0.117834 -0.335726 -0.023425 0.045889 -0.069853 0.037624 -0.016412 -0.601932 -0.000696 0.000212 0.104985 0.007920 -0.036938 -0.349822 0.157337 -0.524402 -0.015842 0.050482 -0.000592

Thanks again!
