### ISSUE TITLE
Converting custom OpenSim Musculoskeletal Model to MuJoCo model

### ISSUE THREAD

**Issue by asheesh1996** [MyoHub/myo_sim#5]
Hi,
How can I convert my custom Musculoskeletal Model to MuJoCo model? I would like to use the converted model in the [myosuite ](https://github.com/facebookresearch/myosuite) environment?

**Comment by Vittorio-Caggiano** [comment]
Hi @asheesh1996 so sorry I missed this issue. 
Are you interested in contributing your model or just to interface it with MyoSuite?
If you are interested in contributing it, what is your model about? How did you validate it?

**Comment by asheesh1996** [comment]
I have validated it in opensim, I would like to interface it with myosuite and test my model.

**Comment by Vittorio-Caggiano** [comment]
you will need to convert it to mujoco first e.g. you could use [O2Mconverter](https://github.com/aikkala/O2MConverter)

**Comment by Vittorio-Caggiano** [comment]
@asheesh1996 I will close this for now but please let us know if you want feedback on the model to contribute it to the community
