### ISSUE TITLE
Question about calling the 'gym.make' function and associated file for 'myoElbowPose1D6MRandom-v0'

### ISSUE THREAD

**Issue by AyanT01** [MyoHub/myo_sim#7]
Hello,
I have a question regarding the following code snippet:
import myosuite
import gym
env = gym.make('myoElbowPose1D6MRandom-v0')
env.reset()
for _ in range(1000):
    env.sim.render(mode='window')
    env.step(env.action_space.sample()) # take a random action
env.close()
In this code, I noticed the usage of the gym.make function with the argument 'myoElbowPose1D6MRandom-v0'. I'm curious about how this function call is handled and if there is a specific file that controls the environment with the name 'myoElbowPose1D6MRandom-v0'.

Could you please provide some insight into the internal workings of gym.make and how it retrieves and initializes the specified environment? Additionally, I would appreciate any information on the file structure or configuration associated with the environment named 'myoElbowPose1D6MRandom-v0'.

Thank you in advance for your assistance!

Best regards,
Abdul haq Ayantayo

**Comment by Vittorio-Caggiano** [comment]
Hi @AyanT01 the `myo_sim` project is a repository of models. Can you please move this to the [MyoSuite Issue](https://github.com/facebookresearch/myosuite/issues) ?

**Comment by AyanT01** [comment]
Thanks for letting me know!!
